// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: protobufs/hello.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloApiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   bool `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	MyTest bool `protobuf:"varint,2,opt,name=my_test,json=myTest,proto3" json:"my_test,omitempty"`
}

func (x *HelloApiRequest) Reset() {
	*x = HelloApiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloApiRequest) ProtoMessage() {}

func (x *HelloApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloApiRequest.ProtoReflect.Descriptor instead.
func (*HelloApiRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloApiRequest) GetType() bool {
	if x != nil {
		return x.Type
	}
	return false
}

func (x *HelloApiRequest) GetMyTest() bool {
	if x != nil {
		return x.MyTest
	}
	return false
}

type HelloApiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` //  repeated SimilarVars similar_vars = 1;
}

func (x *HelloApiResponse) Reset() {
	*x = HelloApiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloApiResponse) ProtoMessage() {}

func (x *HelloApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloApiResponse.ProtoReflect.Descriptor instead.
func (*HelloApiResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloApiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protobufs_hello_proto protoreflect.FileDescriptor

var file_protobufs_hello_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x73, 0x22, 0x3e, 0x0a, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x70, 0x69, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x79, 0x5f,
	0x74, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6d, 0x79, 0x54, 0x65,
	0x73, 0x74, 0x22, 0x2c, 0x0a, 0x10, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x70, 0x69, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x32, 0x53, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x43, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x70, 0x69, 0x12, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x70,
	0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x73, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufs_hello_proto_rawDescOnce sync.Once
	file_protobufs_hello_proto_rawDescData = file_protobufs_hello_proto_rawDesc
)

func file_protobufs_hello_proto_rawDescGZIP() []byte {
	file_protobufs_hello_proto_rawDescOnce.Do(func() {
		file_protobufs_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_hello_proto_rawDescData)
	})
	return file_protobufs_hello_proto_rawDescData
}

var file_protobufs_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobufs_hello_proto_goTypes = []any{
	(*HelloApiRequest)(nil),  // 0: protobufs.HelloApiRequest
	(*HelloApiResponse)(nil), // 1: protobufs.HelloApiResponse
}
var file_protobufs_hello_proto_depIdxs = []int32{
	0, // 0: protobufs.HelloService.HelloApi:input_type -> protobufs.HelloApiRequest
	1, // 1: protobufs.HelloService.HelloApi:output_type -> protobufs.HelloApiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobufs_hello_proto_init() }
func file_protobufs_hello_proto_init() {
	if File_protobufs_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufs_hello_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HelloApiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_hello_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HelloApiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufs_hello_proto_goTypes,
		DependencyIndexes: file_protobufs_hello_proto_depIdxs,
		MessageInfos:      file_protobufs_hello_proto_msgTypes,
	}.Build()
	File_protobufs_hello_proto = out.File
	file_protobufs_hello_proto_rawDesc = nil
	file_protobufs_hello_proto_goTypes = nil
	file_protobufs_hello_proto_depIdxs = nil
}
